//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class3.
    /// </summary>
    // *** Start programmer edit section *** (NewClass3 CustomAttributes)

    // *** End programmer edit section *** (NewClass3 CustomAttributes)
    [AutoAltered()]
    [Caption("New class3")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass3E", new string[] {
            "asd3 as \'Asd3\'"})]
    public class NewClass3 : ICSSoft.STORMNET.DataObject
    {

        private string fasd3;

        private IIS.Test.NewClass2 fNewClass2;

        // *** Start programmer edit section *** (NewClass3 CustomMembers)

        // *** End programmer edit section *** (NewClass3 CustomMembers)


        /// <summary>
        /// asd3.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.asd3 CustomAttributes)

        // *** End programmer edit section *** (NewClass3.asd3 CustomAttributes)
        [StrLen(255)]
        public virtual string asd3
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.asd3 Get start)

                // *** End programmer edit section *** (NewClass3.asd3 Get start)
                string result = this.fasd3;
                // *** Start programmer edit section *** (NewClass3.asd3 Get end)

                // *** End programmer edit section *** (NewClass3.asd3 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.asd3 Set start)

                // *** End programmer edit section *** (NewClass3.asd3 Set start)
                this.fasd3 = value;
                // *** Start programmer edit section *** (NewClass3.asd3 Set end)

                // *** End programmer edit section *** (NewClass3.asd3 Set end)
            }
        }

        /// <summary>
        /// мастеровая ссылка на шапку IIS.Test.NewClass2.
        /// </summary>
        // *** Start programmer edit section *** (NewClass3.NewClass2 CustomAttributes)

        // *** End programmer edit section *** (NewClass3.NewClass2 CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "NewClass2"})]
        public virtual IIS.Test.NewClass2 NewClass2
        {
            get
            {
                // *** Start programmer edit section *** (NewClass3.NewClass2 Get start)

                // *** End programmer edit section *** (NewClass3.NewClass2 Get start)
                IIS.Test.NewClass2 result = this.fNewClass2;
                // *** Start programmer edit section *** (NewClass3.NewClass2 Get end)

                // *** End programmer edit section *** (NewClass3.NewClass2 Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass3.NewClass2 Set start)

                // *** End programmer edit section *** (NewClass3.NewClass2 Set start)
                this.fNewClass2 = value;
                // *** Start programmer edit section *** (NewClass3.NewClass2 Set end)

                // *** End programmer edit section *** (NewClass3.NewClass2 Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "NewClass3E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass3E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass3E", typeof(IIS.Test.NewClass3));
                }
            }
        }
    }

    /// <summary>
    /// Detail array of NewClass3.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfNewClass3 CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfNewClass3 CustomAttributes)
    public class DetailArrayOfNewClass3 : ICSSoft.STORMNET.DetailArray
    {

        // *** Start programmer edit section *** (IIS.Test.DetailArrayOfNewClass3 members)

        // *** End programmer edit section *** (IIS.Test.DetailArrayOfNewClass3 members)


        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type NewClass3 by index.
        /// </summary>
        /// <summary>
        /// Adds object with type NewClass3.
        /// </summary>
        public DetailArrayOfNewClass3(IIS.Test.NewClass2 fNewClass2) : 
                base(typeof(NewClass3), ((ICSSoft.STORMNET.DataObject)(fNewClass2)))
        {
        }

        public IIS.Test.NewClass3 this[int index]
        {
            get
            {
                return ((IIS.Test.NewClass3)(this.ItemByIndex(index)));
            }
        }

        public virtual void Add(IIS.Test.NewClass3 dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}

