//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class1.
    /// </summary>
    // *** Start programmer edit section *** (NewClass1 CustomAttributes)

    // *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [Caption("New class1")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass1E", new string[] {
            "asd as \'Asd\'"})]
    [View("NewClass1L", new string[] {
            "asd as \'Asd\'"})]
    public class NewClass1 : ICSSoft.STORMNET.DataObject
    {

        private int fasd;

        // *** Start programmer edit section *** (NewClass1 CustomMembers)

        // *** End programmer edit section *** (NewClass1 CustomMembers)


        /// <summary>
        /// asd.
        /// </summary>
        // *** Start programmer edit section *** (NewClass1.asd CustomAttributes)

        // *** End programmer edit section *** (NewClass1.asd CustomAttributes)
        public virtual int asd
        {
            get
            {
                // *** Start programmer edit section *** (NewClass1.asd Get start)

                // *** End programmer edit section *** (NewClass1.asd Get start)
                int result = this.fasd;
                // *** Start programmer edit section *** (NewClass1.asd Get end)

                // *** End programmer edit section *** (NewClass1.asd Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass1.asd Set start)

                // *** End programmer edit section *** (NewClass1.asd Set start)
                this.fasd = value;
                // *** Start programmer edit section *** (NewClass1.asd Set end)

                // *** End programmer edit section *** (NewClass1.asd Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "NewClass1E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass1E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass1E", typeof(IIS.Test.NewClass1));
                }
            }

            /// <summary>
            /// "NewClass1L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass1L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass1L", typeof(IIS.Test.NewClass1));
                }
            }
        }
    }
}

